versions:
  - vertx: 4.2.0
pipelines:
  - name: smallrye
    steps:
      - repository: cescoffier/smallrye-mutiny-vertx-bindings
        branchOrCommit: bump-to-vertx-4.2.0
        commands:
          - mvn clean install
        dependencies:
          vertx.version: vertx
      - repository: smallrye/smallrye-reactive-messaging
        dependencies:
          vertx.version: vertx
          "smallrye-vertx-mutiny-clients.version": smallrye/smallrye-mutiny-vertx-bindings
      - repository: smallrye/smallrye-stork
        dependencies:
          vertx.version: vertx
        commands:
          - mvn clean install -DskipTests

  - name: quarkus
    steps:
      - repository: cescoffier/quarkus-http
        branchOrCommit: vertx-4.2.0-integration
        commands:
          - mvn clean install -DskipTests
        dependencies:
          vertx.version: vertx

      - repository: cescoffier/quarkus
        branchOrCommit: vertx-4.2.0.beta1-integration
        version: 999-SNAPSHOT
        dependencies:
          vertx.version: vertx
          "smallrye-reactive-messaging.version": smallrye/smallrye-reactive-messaging
          "smallrye-mutiny-vertx-binding.version": smallrye/smallrye-mutiny-vertx-bindings
          "quarkus-http.version": cescoffier/quarkus-http
        commands:
          - mvn clean install -Dquickly
          - mvn install -f extensions/vertx
          - mvn install -f extensions/vertx-http
          - mvn install -f extensions/reactive-routes
          - mvn install -f extensions/vertx-graphql
          - mvn install -f extensions/grpc-common
          - mvn install -f extensions/grpc
          - mvn install -f extensions/smallrye-reactive-messaging-kafka
          - mvn install -f extensions/smallrye-reactive-messaging
          - mvn install -f extensions/smallrye-reactive-messaging-amqp
          - mvn install -f extensions/smallrye-reactive-messaging-mqtt
          - mvn install -f extensions/reactive-messaging-http
          - mvn install -f extensions/reactive-pg-client
          - mvn install -f extensions/reactive-mysql-client
          - mvn install -f extensions/reactive-mssql-client
          - mvn install -f extensions/reactive-db2-client
          - mvn install -f extensions/reactive-datasource
          - mvn verify -Dsurefire.timeout=1200 -Dtest-containers -Dstart-containers -Dformat.skip -DskipDocs -Dquarkus.test.hang-detection-timeout=60 -pl integration-tests/vertx -pl integration-tests/vertx-http -pl integration-tests/vertx-graphql -pl integration-tests/vertx-web -pl integration-tests/vertx-web-jackson
          - mvn verify -Dsurefire.timeout=1200 -Dtest-containers -Dstart-containers -Dformat.skip -DskipDocs -Dquarkus.test.hang-detection-timeout=60 -pl integration-tests/reactive-messaging-kafka -pl integration-tests/reactive-messaging-amqp -pl integration-tests/reactive-messaging-http
          - mvn verify -Dsurefire.timeout=1200 -Dtest-containers -Dstart-containers -Dformat.skip -DskipDocs -Dquarkus.test.hang-detection-timeout=60 -pl integration-tests/grpc-plain-text-mutiny -pl integration-tests/grpc-streaming -pl integration-tests/grpc-mutual-auth -pl integration-tests/grpc-plain-text-gzip -pl integration-tests/grpc-hibernate-reactive -pl integration-tests/grpc-hibernate -pl integration-tests/grpc-health
          - mvn verify -Dsurefire.timeout=1200 -Dtest-containers -Dstart-containers -Dformat.skip -DskipDocs -Dquarkus.test.hang-detection-timeout=60 -pl integration-tests/rest-client-reactive  -pl integration-tests/rest-client-reactive-multipart
          - mvn verify -Dtest-containers -Dstart-containers -Dquarkus.native.native-image-xmx=5g -Dnative -Dnative.surefire.skip -Dformat.skip -Dno-descriptor-tests -DskipDoc -pl integration-tests/vertx -pl integration-tests/vertx-http -pl integration-tests/vertx-web -pl integration-tests/vertx-web-jackson -pl integration-tests/vertx-graphql

