---
name: Build Vert.x 4.2.x
on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    - cron: '0 2 * * *'

jobs:
  build-constructor:
    runs-on: ubuntu-18.04
    name: Build Constructor
    steps:
      - uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: maven-java-11
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        name: set up jdk 11
        with:
          distribution: temurin
          java-version: 11
      - name: Give me some space
        run: |
          time docker images
          time docker rmi node:12 node:12-alpine node:14 node:14-alpine 
          time sudo rm -rf /usr/share/dotnet
          time sudo rm -rf /usr/share/swift          
      - name: Build Constructor
        run: mvn -f constructor/pom.xml -B clean verify
      - name: Run Pipeline
        run: java -jar constructor/target/quarkus-app/quarkus-run.jar build vertx4.2.x-to-quarkus.yaml
      - name: Prepare artifact
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: constructor
          path: |
            constructor.zip
            report.html
      - name: Report
        if: always()
        shell: bash
        run: |      
          java -jar constructor/target/quarkus-app/quarkus-run.jar report \
            issueNumber=7 \
            runId=${{ github.run_id }} \
            status=${{ job.status }} \
            token=${{ secrets.GH_API }} \
            issueRepo=${{ github.repository }} \
            thisRepo=${{ github.repository }}      
