---
name: Build
on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-constructor:
    runs-on: ubuntu-18.04
    name: Build Constructor
    steps:
      - uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: maven-java-11
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        name: set up jdk 11
        with:
          distribution: temurin
          java-version: 11
      - name: Give me some space
        run: |
          time docker images
          time docker rmi node:10 node:12 node:10-alpine node:12-alpine node:14 node:14-alpine 
          time sudo rm -rf /usr/share/dotnet
          time sudo rm -rf /usr/share/swift          
      - name: Build Constructor
        run: mvn -f constructor/pom.xml -B clean verify
      - name: Run Pipeline
        run: java -jar constructor/target/quarkus-app/quarkus-run.jar vertx-to-quarkus.yaml
      - name: Prepare artifact
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: constructor
          path: |
            constructor.zip
            report.html
